extends RefCounted
var game
var checks=[]
func check(ok:bool,label:String)->void:
	if not ok:
		push_error("QA_FAILED: "+label)
		game.get_tree().quit(1)
		assert(ok,label)
	checks.append(label)
	print("PASS: "+label)
func wait(t:float)->void: await game.get_tree().create_timer(t).timeout
func drag(a:Vector2,b:Vector2)->void:
	var e=InputEventMouseButton.new();e.button_index=MOUSE_BUTTON_LEFT;e.position=a;e.pressed=true
	game.get_viewport().push_input(e)
	var m=InputEventMouseMotion.new();m.position=b;m.button_mask=MOUSE_BUTTON_MASK_LEFT
	game.get_viewport().push_input(m)
	e=InputEventMouseButton.new();e.button_index=MOUSE_BUTTON_LEFT;e.position=b;e.pressed=false
	game.get_viewport().push_input(e)
func conversation()->void:
	game.v4.open_conversation();game.v4.dialogue_action()
	game.backpack.choose(true);game.backpack.choose(true)
	game.v4.close_conversation()
func guest(region:int,index:int)->void:
	game.stage=0;game.selected.clear();game.service.eating=false
	game.economy.map_index=region;game.order_index=index
	game.v4.new_guest();game.economy.apply_map();game._set_customer();game._refresh()
func run(g)->void:
	game=g
	game.screenshot_dir=ProjectSettings.globalize_path("user://qa_verify_v4")
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(game.screenshot_dir))
	game.auto_time=false;game.auto_weather=false;game.hour=10;game.weather=0
	await wait(.3)
	check(not game.v4.dialogue_panel.visible,"No untriggered customer speech or choices")
	check(game.slots.is_empty(),"Removed floating ingredient-slot UI")
	check(game.coin_texture.get_width()==11,"Money uses an actual pixel texture, not a font symbol")
	check(game.v4.day_screen.text=="第 01 天" and not game.chapter_label.get_parent().visible,"Day appears only on robot lower screen")
	check(not game.v4.prop_meshes[0].visible,"No added table in front of RV")
	check(not game.world.find_child("Pot_Front",true,false).visible and game.world.find_child("CleanStoveBehindReplacementPot",true,false)!=null,"Old crooked pot layer removed and its baked footprint covered")
	game.v4.guide_seconds=0
	await wait(.05)
	check(not game.service.guide_panel.visible,"Robot dialogue hides when speech ends")
	game.v4.speak_guide();await wait(.05)
	check(game.service.guide_panel.visible,"Click-triggered robot guidance")
	game.v4.guide_seconds=0
	await wait(.05)
	await game._capture("01_原有布局与人物比例.png")
	game._click_for_qa(Vector2(704,305));await wait(.05)
	check(game.v4.dialogue_open,"Clicking the customer opens their order")
	check(not game.service.story_button.visible,"Story options hidden before conversation")
	game.v4.dialogue_action();await wait(.05)
	check(game.service.story_button.visible and game.backpack.alternate.visible,"Conversation reveals two choices")
	game.backpack.choose(true);game.backpack.choose(true)
	check(game.backpack.conversation_complete and game.service.journal.message,"Correct dialogue sequence links Joe to Arlan")
	await game._capture("02_按需出现的像素对话.png")
	game.v4.close_conversation()
	check(not game.service.story_button.visible and not game.v4.dialogue_panel.visible,"Closing conversation hides choices and speech")
	check(game.prep.plant_meshes[0].material_override.get_shader_parameter("art").resource_path.ends_with("rv_atlas_v3.png"),"Original hydroponic art reused")
	check(game.prep.packet.material_override.get_shader_parameter("art").resource_path.ends_with("rv_atlas_v3.png"),"Original countertop packet reused")
	var rain=game.world.find_child("WeatherOutsideWindow",true,false)
	check(rain.get_aabb().position.z+rain.position.z<game.character.get_aabb().position.z,"Rain is behind the customer")
	var beef_stock=game.prep.stock[0]
	drag(Vector2(894,546),Vector2(680,596))
	check(game.prep.board_item==0,"Whole beef drags from original bin to original board")
	for i in range(3):
		game._click_for_qa(Vector2(680+i*16,596));await wait(.4)
	check(game.prep.cuts==3,"Three deliberate chopping strokes")
	drag(Vector2(723,602),Vector2(440,526))
	check(game.selected.has(0) and game.prep.stock[0]==beef_stock-1,"Prepared meat drops into pot once")
	game._click_for_qa(Vector2(960,650))
	check(game.selected.has(1) and game.v4.eggs.size()==8,"Raw eggs in two rows of recessed holes")
	check(not game.v4.has_water and not game.v4.seasoned,"Empty pot distinct before ignition")
	game._cook();await wait(.1)
	check(game.v4.has_water and not game.v4.seasoned,"Ignition adds clear water, not colored broth")
	check(game.v4.vessel.material_override.get_shader_parameter("frame_rect").x>0.3,"Clear-water pot art selected")
	await game._capture("03_水平锅口与清水.png")
	game._process(4)
	game._click_for_qa(Vector2(263,599));await wait(1.7)
	check(game.stage==2 and game.prep.packet_stage==1,"First bag click tears without adding noodles")
	check(not game.v4.seasoned,"Tearing packaging does not color water")
	game._click_for_qa(Vector2(263,599));await wait(1.05)
	check(game.stage==3 and game.v4.seasoned,"Second click drops noodle cake and seasoning into colored broth")
	drag(Vector2(1170,450),Vector2(440,527))
	drag(Vector2(1170,243),Vector2(440,527))
	check(game.selected.has(7) and game.selected.has(6),"Original vegetables drag into cooking pot")
	check(game.food_count()==4,"Four food ingredients fill the pot")
	check(game._select(3),"Seasoning can be added after four food ingredients")
	check(not game._select(4,true),"A fifth food ingredient is rejected")
	check(game.v4.floats[0].visible and game.v4.floats[1].visible and game.v4.floats[7].visible,"Prepared ingredients have floating pot images")
	game.prep.water(2);game.prep.tick(60)
	check(game.prep.farm_growth[2]==0,"One watering cannot regrow vegetables")
	game.prep.water(2);game.prep.tick(31)
	check(game.prep.farm_growth[2]==1,"Two waterings allow regrowth")
	game._process(5);game._process(3600)
	check(game.stage==4,"Cooking stays untimed with automatic warm keeping")
	var previous_dusk=game.sunset_amount
	game.hour=18;game._apply_lighting(.016);game.v4.guide_seconds=0
	check(absf(game.sunset_amount-previous_dusk)<.01,"Time change interpolates naturally without a color jump")
	game._apply_lighting(20)
	await wait(.05)
	await game._capture("04_汤底食材与黄昏室内光照.png")
	game._cook();var coins=game.coins
	drag(Vector2(690,568),Vector2(704,446))
	check(game.service.eating and game.stage==6,"Bowl drops onto existing gray window ledge")
	check(game.coins==coins,"No payment before eating")
	game._next_customer()
	check(game.order_index==0 and game.service.eating,"Cannot skip the bite")
	await wait(1.0)
	check(game.v4.bite_count==1 and game.service.last_frame==1,"One chopstick bite, no repeated eating")
	var bowl_place=game.bowl.position
	await game._capture("05_长板上夹面不端碗.png")
	await wait(.3)
	check(game.bowl.position.distance_to(bowl_place)<.001,"The bowl remains on the ledge during the bite")
	await wait(1.45)
	check(game.service.last_frame==2 and not game.service.eating,"Expression changes only after swallowing")
	check(game.coins==coins+20 and game.v4.total_tips==8,"Correct meal pays 12 plus 8 saved jar tips")
	check(game.backpack.gifts.has("老乔"),"Perfect meal and ordered dialogue award a personal keepsake")
	check(not game.v4.coin_flights.is_empty(),"Tip coins fly toward glass jar")
	await game._capture("06_评价与金币飞入存钱罐.png")
	var paid=game.coins;game.service.complete_meal()
	check(game.coins==paid,"Meal cannot pay twice")
	game.v4.advance_review()
	check(game.service.last_frame==0 and game.v4.review_line==1,"Next speech line restores neutral expression")
	game.v4.advance_review();await wait(.05)
	check(not game.v4.dialogue_panel.visible and game.v4.farewell_done,"Thank-you goodbye dismisses the dialogue")
	await game._capture("07_道别后恢复干净画面.png")
	game._next_customer();await wait(.05)
	check(game.service.order().name=="禾苗","Road region second customer retained")
	game.stage=5;game._refresh();var stock=game.prep.stock.duplicate()
	drag(Vector2(690,568),Vector2(1210,670))
	check(game.stage==0 and game.service.discarded==1 and game.prep.stock==stock,"Large waste bin discards without refund")
	game.stage=5;game._refresh();game._serve();await wait(2.8)
	check(game.service.satisfaction==10 and game.service.last_tip==0,"Incorrect order receives lower satisfaction and no tip")
	game.v4.advance_review();game.v4.advance_review();game._next_customer();await wait(.05)
	check(game.v4.is_barter() and game.service.order().name=="拾风","Homeless barter guest appears on old road")
	game.v4.open_conversation();var before_refusal=game.coins
	check(game.talk_button.text=="接受换餐" and game.v4.conversation_close.text=="拒绝","Barter offers a genuine accept/refuse choice")
	await game._capture("08_流浪旅人提出纪念品换餐.png")
	game.v4.decline_barter();await wait(.05)
	check(game.coins==before_refusal and not game.backpack.gifts.has("拾风") and game.order_index==0,"Refusing barter costs nothing and lets visitor leave")
	guest(0,2);await wait(.05);game.v4.open_conversation();game.v4.dialogue_action()
	check(game.v4.barter_accepted,"Accepting barter records agreement")
	game.selected=[1,5];game.stage=5;game._refresh();var before_barter=game.coins
	game._serve();await wait(2.8)
	check(game.coins==before_barter and game.service.last_tip==0,"Barter guest pays no money or tip")
	check(game.backpack.gifts.has("拾风"),"Promised bird whistle arrives after meal")
	game.backpack.pinned=true;await wait(.5);game.backpack.show_item(8)
	check(game.backpack.cells[8].pic.texture!=null,"Barter keepsake appears as an inventory image")
	await game._capture("09_铜鸟哨收入顶柜背包.png")
	game.backpack.pinned=false;game.backpack.pointer=Vector2(-30,-30);await wait(.5)
	guest(0,0)
	for region in range(3):
		if game.economy.map_index!=region: check(game.economy.travel(region),"Travel to region "+str(region))
		var ids=[]
		for good in game.economy.local_goods():
			if good.has("food") and int(good.food)>=8: ids.append(int(good.food))
		check(ids==[8+region],"Unique regional specialty "+str(region))
		game.coins=100;var id=8+region;var before=game.prep.stock[id]
		check(game.economy.buy(game.economy.local_goods().size()-1),"Buy local specialty "+str(region))
		check(game.prep.stock[id]==before+4,"Regional purchase enters pantry "+str(region))
		game._click_for_qa(Vector2(896+region*59,589))
		if not game.selected.has(id): print("INPUT_DIAG ",{"allowed":game.prep.input_allowed(),"help":game.help_panel.visible,"menu":game.economy.panel.visible,"backpack":game.backpack.panel.visible,"layers":game.show_layers,"stage":game.stage,"customer":game.service.order().name,"selection":game.selected,"stock":game.prep.stock,"drag":game.service.drag_kind})
		check(game.selected.has(id),"Specialty comes from its original countertop bin "+str(region))
		game._reset_bowl()
		for actor in range(2):
			guest(region,actor);game.hour=10;game.weather=0;game.v4.guide_seconds=0;game._apply_lighting(20);await wait(.08)
			await game._capture("10_区域%d_人物%d.png" % [region,actor])
		game.economy.open_menu();game.economy.tab="shop";game.economy.redraw()
		await game._capture("11_区域%d专属商店.png" % region)
		game.economy.panel.hide()
	game.hour=22;game._set_weather(1);game._process(3);await wait(.1)
	game._apply_lighting(20);game._apply_lighting(20);await wait(.05)
	await game._capture("12_雨在客人后方与车内暖光.png")
	game.economy.accept_job();game.economy.panel.hide();game.economy.delivery_mode=true
	game.selected=game.economy.job.need.duplicate();game.stage=5
	check(game.economy.pack_delivery(),"Untimed delivery packs regional ingredients")
	check(game.economy.travel(int(game.economy.job.destination)),"Carry hot delivery between regions")
	check(game.economy.deliver() and not game.economy.deliver(),"Delivery pays once")
	guest(1,0);await wait(.05);conversation()
	check(game.service.journal.battery,"Arlan hands over battery after Joe message")
	guest(1,1);await wait(.05);conversation()
	check(game.service.journal.radio and not game.service.journal.battery,"Adeng repairs the radio")
	guest(0,1);await wait(.05);conversation()
	check(game.service.journal.seeds,"Forecast permits Hemiao to entrust seeds")
	guest(2,0);await wait(.05);conversation()
	check(game.service.journal.clinic,"Xia plants seeds at the clinic")
	guest(2,1);await wait(.05);conversation()
	check(game.service.journal.warm_route,"Connected stories unlock warm-meal ferry")
	game.audio.music_volume=.43;game.save_path="user://qa_v4_roundtrip.json";game.qa_save_enabled=true
	game._save();var saved=game.coins;game.coins=0;game.v4.total_tips=0;game._load_save()
	check(game.coins==saved and game.v4.total_tips==8,"Save restores currency and physical jar total")
	check(game.backpack.gifts.has("拾风") and game.service.journal.radio,"Barter keepsake and story links persist")
	check(is_equal_approx(game.audio.music_volume,.43),"Separate BGM volume persists")
	check(game.audio.music.stream.get_length()>75 and game.audio.music.stream.loop,"Original warm BGM is a looping audio stream")
	game.audio.duck=0;game.audio.tick(3);var loud=game.audio.music.volume_db
	game.audio.play_at("chop1",0,-15);game.audio.tick(.4)
	check(game.audio.music.volume_db<loud-4,"BGM ducks beneath ASMR actions")
	game.sound_off=true;game.audio.tick(4)
	check(game.audio.music.volume_db<=-79,"Mute includes BGM")
	game.sound_off=false
	game.v4.close_conversation();var motion=InputEventMouseMotion.new();motion.position=Vector2(480,35);game.get_viewport().push_input(motion)
	await wait(.4)
	check(game.service.cabinet_amount==1 and game.backpack.panel.visible,"Hover opens the original hinged cabinet and inventory")
	motion=InputEventMouseMotion.new();motion.position=Vector2(90,700);game.get_viewport().push_input(motion);await wait(.4)
	check(game.service.cabinet_amount==0 and not game.backpack.panel.visible,"Leaving closes cabinet")
	var f=FileAccess.open(ProjectSettings.globalize_path("user://qa_verify_v4_result.json"),FileAccess.WRITE)
	f.store_string(JSON.stringify({"passed":checks.size(),"checks":checks,"native_godot_tested":true,"characters":7,"regions":3,"bgm_seconds":game.audio.music.stream.get_length()},"  "));f.close()
	print("V4_QA_COMPLETE "+str(checks.size()))
	game._shutdown()
