extends RefCounted
var game
var count=0
func check(ok:bool,label:String):
	if not ok:
		push_error("SIX_FAILED: "+label);game.get_tree().quit(1);assert(ok,label)
	count+=1;print("PASS ",count,": ",label)
func capture(name:String):
	if DisplayServer.get_name()!="headless":await game._capture(name)
func move(p:Vector2):
	var ev=InputEventMouseMotion.new();ev.position=p;ev.global_position=p;game.get_viewport().push_input(ev)
func same_region(a:Image,b:Image,rect:Rect2i)->bool:
	for x in range(rect.position.x,rect.end.x):
		for y in range(rect.position.y,rect.end.y):
			if a.get_pixel(x,y)!=b.get_pixel(x,y):return false
	return true
func reset_meal():
	game.fieldlife.closeup.hide();game.fieldlife.close_fridge();game.fieldlife.pointer=Vector2(640,680)
	game.stage=0;game.selected.clear();game.simmer.reset();game.prep.clear_board();game.prep.reset_packet();game.v5.cancel_transition();game.v4.new_guest();game._refresh()
func run(g):
	game=g;await game.get_tree().create_timer(.2).timeout;game.set_process(false)
	game.screenshot_dir="user://qa_verify_six"
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(game.screenshot_dir))
	game.auto_time=false;game.auto_weather=false
	check(game.prep.stock.size()==14 and game.toppings.size()==14,"14 ingredients have matching inventory and bowl artwork")
	check(not game.tutorial.active,"QA does not interrupt play with tutorial")
	game.prep.farm_growth[0]=0;game.prep.farm_water[0]=0;game.prep.water_store=8;game.irrigation.level=8
	check(game.irrigation.start(0),"Empty tray starts watering")
	check(game.prep.water_store==7 and game.prep.farm_water[0]==0,"Water reserves once and plant is not watered before flow finishes")
	check(not game.irrigation.start(1),"One faucet cannot start two simultaneous flows")
	game.irrigation.tick(1.2)
	check(game.irrigation.valve>.9 and game.irrigation.level>7 and game.irrigation.level<8,"Faucet open and waterline descends gradually")
	await capture("01_阀门与水位.png")
	game.irrigation.tick(1.3)
	check(game.irrigation.active==-1 and game.irrigation.valve==0 and game.prep.farm_water[0]==1,"Faucet closes after one watering")
	check(game.irrigation.start(0),"Second watering starts")
	game.irrigation.tick(1.0);var irrigation_save=game.irrigation.to_save();game.irrigation.restore(irrigation_save);game.irrigation.tick(1.5)
	check(game.prep.farm_water[0]==2 and game.prep.water_store==6,"Resumed watering completes without charging twice")
	game.prep.tick(3)
	check(game.prep.farm_growth[0]>0,"Growth starts after enough water")
	check(not game.irrigation.start(0),"Full roots do not waste water")
	reset_meal();game.economy.map_index=0;game.order_index=0;game._set_customer();game.backpack.tick()
	game.v4.open_conversation();game.v4.dialogue_action();game.backpack.choose(true);game.backpack.choose(true)
	check(game.backpack.conversation_complete and not game.service.journal.message,"Correct dialogue remembers promise but waits for perfect meal")
	game.v4.close_conversation();game._click_for_qa(Vector2(895,548))
	check(game.prep.board_item==0 and game.selected.is_empty(),"Click whole beef puts it on board")
	for i in range(3):
		game._click_for_qa(Vector2(691,587));await game.get_tree().create_timer(.14).timeout;game.prep.tick(.4)
	check(game.prep.cuts==3 and not game.selected.has(0),"Three cuts do not automatically add meat")
	game._click_for_qa(Vector2(691,587));game._click_for_qa(Vector2(973,652));game._click_for_qa(Vector2(1005,546))
	check(game.selected.has(0) and game.selected.has(1) and game.selected.has(3),"Clicked meat, egg, spice go into recipe")
	game._click_for_qa(Vector2(445,561));check(game.stage==1 and game.v4.has_water and not game.v4.seasoned,"Pot click starts clear-water heating")
	game.stage=2;game._refresh();game._click_for_qa(Vector2(270,610));await game.get_tree().create_timer(1.7).timeout
	check(game.prep.packet_stage==1 and game.stage==2,"First packet click only tears packaging")
	game._click_for_qa(Vector2(585,533));await game.get_tree().create_timer(1.05).timeout
	check(game.prep.packet_stage==2 and game.stage==3 and game.v4.seasoned,"Second packet click drops noodles and seasoning")
	game.stage=4;game.simmer.tick(16.3);game._refresh()
	check(game.simmer.quality(1)=="最佳" and game.simmer.quality(0)=="未到最佳","Egg and beef have distinct best doneness")
	game._click_for_qa(game.simmer.rows[1].button.get_global_rect().get_center())
	check(game.simmer.portions[1].lifted,"Real doneness button can lift egg")
	var egg_time=game.simmer.portions[1].time;game.simmer.tick(4)
	check(game.simmer.portions[1].time==egg_time and game.simmer.quality(0)=="最佳","Lifted ingredient stops cooking while meat continues")
	game._click_for_qa(game.simmer.rows[0].button.get_global_rect().get_center());game.v4.update_pot()
	check(not game.v4.floats[0].visible and not game.v4.floats[1].visible,"Lifted ingredients leave pot artwork")
	await capture("02_逐项熟度.png")
	game._click_for_qa(Vector2(445,561))
	check(game.stage==5 and game.simmer.perfect and game.service.score()==100,"Every optimal ingredient produces perfect ramen")
	check(game.v5.guide_override.contains("刚刚好"),"Robot praises perfect ramen")
	await capture("03_完美面在自己的桌上.png")
	check(not game.service.eating,"Serving into bowl does not feed guest")
	game._click_for_qa(Vector2(704,572))
	check(game.stage==6 and game.service.eating,"Clicking finished bowl starts serving")
	game.v4.tick(3)
	check(game.v4.bite_count==1 and not game.service.eating,"Guest takes one bite before review")
	check(game.backpack.gifts.has("老乔") and game.service.journal.message,"Perfect ramen and dialogue grant compass and advance linked story")
	check(game.fieldlife.closeup.visible and game.fieldlife.title.text=="旧黄铜罗盘","Gift reception opens artwork closeup")
	await capture("04_纪念品特写.png")
	game.fieldlife.closeup.hide();game.backpack.show_item(0)
	check(game.fieldlife.closeup.visible,"Inventory reopens same gift closeup")
	game.fieldlife.closeup.hide();game.v4.advance_review();check(game.v4.review_line==1,"Review then returns to normal conversation expression")
	game.v4.advance_review();game.v5.tick(.9);game.v5.tick(.9)
	check(game.stage==0 and game.order_index==1 and game.v4.dialogue_open,"Farewell clears meal and next guest arrives speaking")
	reset_meal();game.economy.map_index=0;game.fieldlife.tick(.1)
	game._click_for_qa(game.fieldlife.hunt_button.get_global_rect().get_center())
	check(game.fieldlife.hunt.visible,"Hunting entrance click is not swallowed by refrigerator")
	check(game.fieldlife.armed,"Entering the hunting view automatically equips the rifle")
	check(game.fieldlife.rifle.texture!=null and game.fieldlife.window_content.clip_contents,"First-person rifle and clipped view through the original cabin window are present")
	var shots_before=game.fieldlife.shots;game._click_for_qa(Vector2(30,500))
	check(game.fieldlife.shots==shots_before,"Cabin frame clicks do not fire outside the window")
	var gun_before=game.fieldlife.rifle.position;move(Vector2(400,300));game.fieldlife.tick(.01)
	check(game.fieldlife.rifle.position!=gun_before,"First-person rifle follows mouse aim")
	var loot=game.prep.stock[11];var cactus=game.prep.stock[8];var first=game.fieldlife.targets[0].pic.get_global_rect().get_center()
	move(game.fieldlife.targets[1].pic.get_global_rect().get_center());game.fieldlife.hunt_paint.queue_redraw()
	await capture("05_远景嫩掌蜥狩猎.png")
	game._click_for_qa(first)
	check(game.prep.stock[11]==loot and game.prep.stock[8]==cactus and game.fieldlife.hit_count==1 and game.fieldlife.drops.size()==2,"Hit drops meat and cactus on the ground without adding inventory")
	check(game.fieldlife.recoil>0 and game.fieldlife.muzzle_time>0 and game.fieldlife.ammo==2,"A shot consumes one round and produces recoil and a brief muzzle flash")
	game.fieldlife.hunt_paint.queue_redraw();await capture("05b_开枪与短枪口光.png")
	game.fieldlife.cooldown=0;game.fieldlife.shoot(first)
	check(game.fieldlife.drops.size()==2,"Same defeated target never yields twice")
	var origin=game.fieldlife.targets[1].pic.position.x;game.fieldlife.tick(.4)
	check(game.fieldlife.targets[1].pic.position.x==origin,"Other prey have a brief reaction delay")
	check(game.fieldlife.casings.size()==1 and game.fieldlife.bolt_age>0,"Cycling the rifle ejects a moving casing without a hand layer")
	await capture("05c_上膛与弹壳.png")
	game.fieldlife.tick(.5)
	check(game.fieldlife.targets[1].pic.position.x>origin,"Other prey then flee at catchable speed")
	game.fieldlife.cooldown=0;var second=game.fieldlife.targets[1].pic.get_global_rect().get_center();move(second);game.fieldlife.hunt_paint.queue_redraw()
	await capture("05a_命中掉落与逃散.png")
	check(game.fieldlife.shoot(second) and game.fieldlife.hit_count==2,"Fast follow-up can catch another prey")
	var meat_pickup=game.fieldlife.drops[0].pic.get_global_rect().get_center();shots_before=game.fieldlife.shots
	game._click_for_qa(meat_pickup)
	check(game.prep.stock[11]==loot+1 and game.fieldlife.shots==shots_before,"Clicking a meat drop picks it up and does not fire")
	check(not game.fieldlife.pick_drop(meat_pickup) and game.prep.stock[11]==loot+1,"Picked-up meat cannot be collected twice")
	game._click_for_qa(game.fieldlife.drops[1].pic.get_global_rect().get_center())
	check(game.prep.stock[8]==cactus+1,"Cactus requires its own manual pickup")
	check(game.fieldlife.to_save().ground.size()==2,"Uncollected loot is retained in the save data")
	game.fieldlife.tick(.6);game.fieldlife.shoot(Vector2(630,200));game.fieldlife.tick(.6)
	shots_before=game.fieldlife.shots;game.fieldlife.shoot(Vector2(630,200))
	check(game.fieldlife.ammo==0 and game.fieldlife.shots==shots_before,"Three-round magazine cannot fire when empty")
	var reload_key=InputEventKey.new();reload_key.keycode=KEY_R;reload_key.pressed=true;game.get_viewport().push_input(reload_key)
	check(game.fieldlife.reload_remaining>0,"R key starts the hands-free reload animation")
	game.fieldlife.tick(.45);var reload_pos=game.fieldlife.rifle.position;game.fieldlife.shoot(Vector2(630,200))
	check(game.fieldlife.shots==shots_before and game.fieldlife.ammo==0 and game.fieldlife.reload_remaining>0,"Reloading blocks shots while the rifle dips and breech moves")
	await capture("05d_无手换弹.png")
	game.fieldlife.tick(.7)
	check(game.fieldlife.ammo==3 and game.fieldlife.reload_remaining==0 and game.fieldlife.rifle.position.y<reload_pos.y,"Reload completes after about one second and raises a full rifle")
	game.fieldlife.shoot(Vector2(630,200));game.fieldlife.tick(.6)
	game._click_for_qa(game.fieldlife.reload_button.get_global_rect().get_center())
	check(game.fieldlife.reload_remaining>0,"Visible reload button works as an alternative to R")
	game.fieldlife.tick(1.1)
	game.fieldlife.leave_hunt();move(Vector2(640,680));game.fieldlife.tick(.5)
	var lower_before:Image
	if DisplayServer.get_name()!="headless":
		await RenderingServer.frame_post_draw;lower_before=game.get_viewport().get_texture().get_image()
	move(Vector2(160,560));game.fieldlife.tick(.3)
	check(game.fieldlife.cold.visible and absf(game.fieldlife.hinge.rotation.y)>.8,"Refrigerator opens with a hinged animation")
	check(is_equal_approx(game.fieldlife.door.mesh.get_aabb().size.y,136*.012265625) and is_equal_approx(game.fieldlife.recess.mesh.get_aabb().size.y,132*.0122656),"Only the upper refrigerator door and its upper cavity are separated")
	if DisplayServer.get_name()!="headless":
		await RenderingServer.frame_post_draw
		check(same_region(lower_before,game.get_viewport().get_texture().get_image(),Rect2i(15,664,205,9)),"Lower refrigerator door pixels remain stationary while the upper door opens")
	move(Vector2(233,554));game.fieldlife.tick(.1)
	check(game.fieldlife.cold.visible,"Hover bridge lets pointer reach cold inventory")
	await capture("06_冷藏与特殊食材.png")
	game._click_for_qa(Vector2(301,575));check(game.prep.board_item==11,"Cold hunted meat is taken to cutting board")
	check(not game.prep.BIN_IDS.has(11),"Cold-only food never occupies ordinary counter trays")
	reset_meal();game.selected=[2];game.simmer.track(2);game.stage=4;game.simmer.tick(12);game.simmer.finalize()
	check(game.simmer.quality(2)=="过熟" and not game.simmer.perfect and game.simmer.penalty()>0,"Overcooked vegetable prevents perfect meal")
	game.service.satisfaction=100;game.backpack.conversation_complete=true;game.backpack.conversation_ok=true;game.economy.map_index=1;game.order_index=0
	check(game.backpack.award_after_meal()=="" and not game.service.journal.battery,"Correct dialogue alone cannot grant consumable")
	reset_meal();game.economy.map_index=0;game.order_index=0;game._set_customer();game.tutorial.restart();game.tutorial.tick(.1)
	check(game.tutorial.overlay.visible,"First-meal tutorial dims actual scene with spotlight")
	await capture("07_机器人逐步教学.png")
	game.tutorial.advance_text();game.tutorial.advance_text();game.tutorial.tick(.1)
	check(game.tutorial.step==game.tutorial.Lesson.MEAT,"Tutorial advances toward real meat interaction")
	game.tutorial.skip()
	game.save_path="user://qa_verify_six_save.json";game.qa_save_enabled=true;game._save()
	var data=JSON.parse_string(FileAccess.get_file_as_string(game.save_path))
	check(data.version==5 and data.has("simmer") and data.has("irrigation") and data.has("tutorial"),"Save carries new gameplay systems")
	var count_saved=game.fieldlife.total_hunted;game.fieldlife.total_hunted=0;game._load_save()
	check(game.fieldlife.total_hunted==count_saved and game.prep.stock.size()==14,"Save reload preserves hunted inventory and progression")
	check(game.fieldlife.to_save().ground.size()==2,"Save reload preserves uncollected ground loot")
	game.hour=15;game.audio.tick(3)
	game.hour=9;game.audio.tick(.3)
	check(game.audio.music_track=="camp_dawn","Morning stall selects its longer daytime theme")
	var hearth_index=game.audio.music_names.find("hearth_road");var dawn_index=game.audio.music_names.find("camp_dawn")
	var hearth_weight=game.audio.music_weights[hearth_index];var dawn_weight=game.audio.music_weights[dawn_index]
	game.fieldlife.open_hunt();game.audio.tick(0.0)
	check(hearth_weight>0 and dawn_weight>0 and is_equal_approx(game.audio.music_weights[hearth_index],hearth_weight) and is_equal_approx(game.audio.music_weights[dawn_index],dawn_weight),"Rapid third-song switch preserves both outgoing weights without cutting their tails")
	game.audio.tick(.6)
	var outgoing=false
	for i in range(game.audio.music_weights.size()):
		if i!=game.audio.music_active and game.audio.music_weights[i]>0:outgoing=true
	check(game.audio.music_track=="hunt_dunes" and game.audio.music_weights[game.audio.music_active]>0 and outgoing,"Entering hunt crossfades outgoing music into the hunting theme")
	game.audio.tick(2.5);game.sound_off=true;game.audio.tick(.1)
	var all_silent=true
	for player in game.audio.music_players:
		if player.volume_db>-80:all_silent=false
	check(all_silent,"Mute silences all four music players during transitions")
	game.sound_off=false;game.fieldlife.leave_hunt();game.audio.tick(3)
	check(game.audio.music_track=="camp_dawn","Leaving hunt returns to the daytime camp theme")
	game.hour=20;game.audio.tick(3)
	check(game.audio.music_track=="camp_lantern" and game.audio.music.stream.loop,"Night camp selects a looping lantern theme")
	for track in ["camp_dawn","camp_lantern","hunt_dunes"]:
		var stream=load("res://assets/asmr/"+track+".ogg")
		check(stream!=null and stream.get_length()>75,"Long-form music duration exceeds 75 seconds: "+track)
	game.qa_save_enabled=false
	print("SIX_QA_COMPLETE ",count)
	game._shutdown()
