extends RefCounted
var game
var checks=[]
func check(ok:bool,label:String)->void:
 if not ok:
  push_error("QA_FAILED: "+label)
  game.get_tree().quit(1)
  assert(ok,label)
 checks.append(label)
 print("PASS: "+label)
func wait(t:float)->void: await game.get_tree().create_timer(t).timeout
func drag(a:Vector2,b:Vector2)->void:
 var e=InputEventMouseButton.new()
 e.button_index=MOUSE_BUTTON_LEFT;e.position=a;e.pressed=true
 game.get_viewport().push_input(e)
 var m=InputEventMouseMotion.new();m.position=b;m.button_mask=MOUSE_BUTTON_MASK_LEFT
 game.get_viewport().push_input(m)
 e=InputEventMouseButton.new();e.button_index=MOUSE_BUTTON_LEFT;e.position=b;e.pressed=false
 game.get_viewport().push_input(e)
func run(g)->void:
 game=g
 game.screenshot_dir=ProjectSettings.globalize_path("user://qa_verify_v3")
 DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(game.screenshot_dir))
 game.auto_time=false;game.auto_weather=false
 await wait(1)
 await game._capture("01_机器人与原图灶台.png")
 check(game.font is FontFile,"Chinese font embedded for web")
 check(game.service.order().name=="老乔","Road region starts with Joe")
 game._talk();game.backpack.choose(true);game.backpack.choose(true)
 check(game.backpack.conversation_complete and game.service.journal.message,"Two dialogue choices remember Joe message")
 game._talk()
 check(game.prep.plant_meshes[0].material_override.get_shader_parameter("art").resource_path.ends_with("rv_atlas_v3.png"),"Original hydroponic artwork reused")
 check(game.prep.packet.material_override.get_shader_parameter("art").resource_path.ends_with("rv_atlas_v3.png"),"Countertop noodle package reuses original reference")
 var rain=game.world.find_child("WeatherOutsideWindow",true,false)
 check(rain.get_aabb().position.z+rain.position.z<game.character.get_aabb().position.z,"Rain remains behind customer")
 var before=game.prep.stock[0]
 drag(Vector2(894,546),Vector2(680,596))
 check(game.prep.board_item==0,"Whole beef dragged to board")
 for i in range(3):
  game._click_for_qa(Vector2(680+i*16,596))
  await wait(.4)
 check(game.prep.cuts==3,"Three manual chopping strokes")
 await game._capture("02_切肉与图像配料.png")
 drag(Vector2(723,602),Vector2(440,526))
 check(game.selected.has(0) and game.prep.stock[0]==before-1,"Cut beef dragged to pot consumes once")
 game._click_for_qa(Vector2(960,650));game._select(3)
 check(game.selected.has(1),"Raw eggs in longest tray")
 check(game.service.slot_icons[0].texture!=null,"Ingredient slots display images")
 game._cook();game._process(4)
 game._click_for_qa(Vector2(263,599))
 await wait(.73)
 await game._capture("03_桌上泡面撕口.png")
 await wait(.85)
 check(game.stage==2 and game.prep.packet_stage==1,"Click countertop bag tears without auto dropping")
 game._click_for_qa(Vector2(263,599))
 await wait(1.0)
 check(game.stage==3,"Second click drops brick and seasoning")
 drag(Vector2(1170,450),Vector2(440,527))
 check(game.selected.has(7) and game.prep.farm_growth[2]==0,"Original spinach dragged directly into cooking pot")
 game.prep.water(2);game.prep.tick(60)
 check(game.prep.farm_growth[2]==0,"One dose cannot regrow plants")
 game.prep.water(2);game.prep.tick(31)
 check(game.prep.farm_growth[2]==1,"Two doses permit regrowth")
 game._process(5);game._process(3600)
 check(game.stage==4,"No timeout or burnt food punishment")
 game._cook()
 var coins=game.coins
 drag(Vector2(690,568),Vector2(690,299))
 check(game.service.eating and game.stage==6,"Bowl dragged to guest begins eating")
 check(game.coins==coins,"No payment before meal is finished")
 game._next_customer()
 check(game.service.eating and game.order_index==0,"Cannot skip eating or double pay")
 await wait(1.1)
 check(game.service.last_frame==1,"One eating pose stays neutral before meal ends")
 await game._capture("04_客人夹面动作.png")
 await wait(4.0)
 check(game.service.last_tip==8 and game.coins==coins+20,"Satisfied guest pays meal and 8 tip")
 check(game.backpack.gifts.has("老乔"),"Correct conversation plus perfect meal awards souvenir")
 var gift_count=game.backpack.gifts.size()
 check(game.backpack.award_after_meal()=="" and game.backpack.gifts.size()==gift_count,"Souvenir is awarded only once")
 await game._capture("05_满足表情与小费.png")
 game._next_customer()
 await wait(.05)
 check(game.service.order().name=="禾苗","Region-specific second guest and story")
 game.stage=5;game._refresh()
 var empty_stock=game.prep.stock.duplicate()
 drag(Vector2(690,568),Vector2(1210,663))
 check(game.stage==0 and game.service.discarded==1,"Bowl dragged to lower-right trash resets serving")
 check(game.prep.stock==empty_stock,"Discard does not refund food")
 game.stage=5;game._refresh();game._serve()
 await wait(5.2)
 check(game.service.satisfaction==10 and game.service.last_tip==0,"Wrong recipe gives disappointed expression and zero tip")
 await game._capture("06_不合口味的反馈.png")
 game._next_customer()
 await wait(.05)
 for region in range(3):
  if game.economy.map_index!=region: check(game.economy.travel(region),"Travel to region "+str(region))
  var ids=[]
  for good in game.economy.local_goods():
   if good.has("food") and int(good.food)>=8: ids.append(int(good.food))
  check(ids==[8+region],"Regional specialty exclusive stock "+str(region))
  game.coins=100
  var id=8+region;var original=game.prep.stock[id]
  check(game.economy.buy(game.economy.local_goods().size()-1),"Purchase local specialty")
  check(game.prep.stock[id]==original+4,"Local specialty inventory retained")
  game._click_for_qa(Vector2(896+region*59,589))
  check(game.selected.has(id),"Local ingredient clickable in real tray")
  game._reset_bowl()
  game.order_index=region%2;game._set_customer();game._refresh()
  game.hour=10
  await wait(.2)
  await game._capture("07_区域"+str(region)+"与顾客.png")
  game.economy.open_menu();game.economy.tab="shop";game.economy.redraw()
  await game._capture("08_区域"+str(region)+"专属商店.png")
  game.economy.panel.hide()
 game.hour=22;game._set_weather(1);game._process(3)
 await game._capture("09_夜雨在客人身后.png")
 game.economy.accept_job();game.economy.panel.hide()
 game.economy.delivery_mode=true;game.selected=game.economy.job.need.duplicate();game.stage=5
 check(game.economy.pack_delivery(),"Regional specialty included in untimed delivery")
 check(game.economy.travel(int(game.economy.job.destination)),"Packed meal travels to destination")
 check(game.economy.deliver(),"Delivery reward at destination")
 check(not game.economy.deliver(),"Delivery cannot be paid twice")
 game.save_path="user://qa_v3_roundtrip.json";game.qa_save_enabled=true
 game._save();var saved_coins=game.coins;game.coins=0;game._load_save()
 check(game.coins==saved_coins,"V3 save restores economy")
 check(game.backpack.gifts.has("老乔") and game.service.journal.message,"Private items and story persist")
 game.economy.map_index=1;game.order_index=0;game.stage=0;game._set_customer();game._refresh();await wait(.05)
 game._talk();game.backpack.choose(true);game.backpack.choose(true)
 check(game.service.journal.battery,"Arlan hands over battery after Joe message")
 game.order_index=1;game._set_customer();game._refresh();await wait(.05)
 game._talk();game.backpack.choose(true);game.backpack.choose(true)
 check(game.service.journal.radio and not game.service.journal.battery,"Adeng repairs radio using Arlan battery")
 game.economy.map_index=0;game.order_index=1;game._set_customer();game._refresh();await wait(.05)
 game._talk();game.backpack.choose(true);game.backpack.choose(true)
 check(game.service.journal.seeds,"Radio forecast unlocks seed handoff")
 game.economy.map_index=2;game.order_index=0;game._set_customer();game._refresh();await wait(.05)
 game._talk();game.backpack.choose(true);game.backpack.choose(true)
 check(game.service.journal.clinic,"Xia plants Hemiao seeds at clinic")
 game.order_index=1;game._set_customer();game._refresh();await wait(.05)
 game._talk();game.backpack.choose(true);game.backpack.choose(true)
 check(game.service.journal.warm_route,"Ferry route connects all six NPC stories after delivery")
 game._talk()
 var motion=InputEventMouseMotion.new();motion.position=Vector2(480,35);game.get_viewport().push_input(motion)
 await wait(.4)
 check(game.service.cabinet_amount==1 and game.backpack.panel.visible,"Hover opens physical cupboard and backpack grid")
 game.backpack.show_item(0)
 await game._capture("10_顶柜背包与罗盘来历.png")
 motion=InputEventMouseMotion.new();motion.position=Vector2(90,700);game.get_viewport().push_input(motion)
 await wait(.4)
 check(game.service.cabinet_amount==0 and not game.backpack.panel.visible,"Leaving closes cupboard")
 for p in game.audio.voices: check(p.bus.begins_with("Foley"),"Independent positional real recording bus")
 var result={"passed":checks.size(),"checks":checks,"rain_behind_customer":true,"regional_cast":6,"regional_specialties":3,"browser_ui_tested":false}
 var f=FileAccess.open(ProjectSettings.globalize_path("user://qa_verify_v3_result.json"),FileAccess.WRITE);f.store_string(JSON.stringify(result,"  "));f.close()
 print("V3_QA_COMPLETE "+str(checks.size()))
 game._shutdown()
